language: node_js
node_js:
  - '4'
  - '6'
before_install:
  - 'npm install npm@latest codeclimate-test-reporter -g'
addons:
  code_climate:
    repo_token: token
after_script:
  - 'npm run gen-coverage && cat coverage/lcov.info | codeclimate-test-reporter'